[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/mechanic"
  to = "/mechanics"
  status = 301

[[redirects]]
  from = "/dashboard/*"
  to = "/login"
  status = 302

[[redirects]]
  from = "/chat/*"  
  to = "/login"
  status = 302

[[redirects]]
  from = "/sitemap"
  to = "/sitemap.xml"
  status = 301

[[redirects]]
  from = "/sitemap-index.xml"
  to = "/sitemap.xml"
  status = 301

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=3600, s-maxage=3600"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"